name: Build and release container for SID
run-name: ${{ gitea.actor }} build
on:
  workflow_dispatch:
# schedule:
#   - cron: "8 11 3 * *" # Build once per month
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitea/**
      - .github/**
      - .gitlab-ci.*

jobs:
  release:
    runs-on: [ amd64 ]
    container: ${{ secrets.DOCKER_REPO }}/actbuildx:latest

    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v3
     
      - name: Set RELEASE_DATE
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v2

#      - name: Cache Docker layers
#        uses: https://github.com/actions/cache@v3
#        with:
#          path: |
#            /tmp/.buildx-cache.latest
#          key: ${{ runner.os }}-buildx-${{ gitea.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx- 

      - name: Login to registry
        uses: https://github.com/docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker AMD64/ARM64 image for latest
        uses: https://github.com/docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:${{ env.RELEASE_DATE }}
#          cache-from: type=local,src=/tmp/.buildx-cache.latest
#          cache-to: type=local,dest=/tmp/.buildx-cache-new.latest
#
#      - name: Rotate the cache for latest
#        run: |
#          set -x
#          rm -rf /tmp/.buildx-cache.latest
#          mv /tmp/.buildx-cache-new.latest /tmp/.buildx-cache.latest
 
