name: Build and release container
run-name: ${{ gitea.actor }} build
on:
  workflow_dispatch:
# schedule:
#   - cron: "20 20 20 * *" # Build once at 3rd
  push:
    branches:
      - nobuild
      #- main
      #- master
    paths-ignore:
      - .gitea/workflows/*

jobs:
  release:
    runs-on: [ amd64 ]
    container: ${{ secrets.DOCKER_REPO }}/actbuildx:latest

    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v3
     
      - name: Set RELEASE_DATE
        run: |
          set -x
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: https://github.com/actions/cache@v3
        with:
          path: |
            /tmp/.buildx-cache.bookworm
          key: ${{ runner.os }}-buildx-${{ gitea.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx- 

      - name: Login to registry
        uses: https://github.com/docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker AMD64/ARM64 image for bookworm
        uses: https://github.com/docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.bookworm
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:bookworm
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:bookworm-${{ env.RELEASE_DATE }}
          cache-from: type=local,src=/tmp/.buildx-cache.bookworm
          cache-to: type=local,dest=/tmp/.buildx-cache-new.bookworm

      - name: Rotate the cache for bookworm
        run: |
          set -x
          rm -rf /tmp/.buildx-cache.bookworm
          mv /tmp/.buildx-cache-new.bookworm /tmp/.buildx-cache.bookworm

