name: Build and release container

on:
  schedule:
    - cron: '0 8 8 * *' # 08:00 on 8th
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitlib-ci.*
      - .gitea/workflows/*
      - .github/workflows/*

jobs:
  release:
    runs-on: ubuntu-latest
    #container: ${{ secrets.DOCKER_REPO }}/actbuildx:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Set RELEASE_DATE
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          echo "REPO_NAME=$(echo ${{ github.repository }} | sed -E 's,.+/([^/]+),\1,')" >> ${GITHUB_ENV}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.buildx-cache.trixie
            /tmp/.buildx-cache.latest
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx- 

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker AMD64/ARM64 image for latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: false
          tags: |
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:${{ env.RELEASE_DATE }}
          cache-from: type=local,src=/tmp/.buildx-cache.latest
          cache-to: type=local,dest=/tmp/.buildx-cache-new.latest

      - name: Rotate the cache for latest
        run: |
          rm -rf /tmp/.buildx-cache.latest
          mv /tmp/.buildx-cache-new.latest /tmp/.buildx-cache.latest

      - name: Build and push Docker AMD64/ARM64 image for trixie
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.trixie
          platforms: linux/amd64, linux/arm64
          push: false
          tags: |
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:trixie
            ${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:trixie-${{ env.RELEASE_DATE }}
          cache-from: type=local,src=/tmp/.buildx-cache.trixie
          cache-to: type=local,dest=/tmp/.buildx-cache-new.trixie

      - name: Rotate the cache for trixie
        run: |
          rm -rf /tmp/.buildx-cache.trixie
          mv /tmp/.buildx-cache-new.trixie /tmp/.buildx-cache.trixie
