name: Build and release container

on:
  schedule:
  - cron: '0 20 * * 0' # Every sunday at 20:00
  push:
    branches:
      - main
      - master
      - CICI 
    paths-ignore:
      - .git*
      #- .github/workflows/*

jobs:
  release:
    runs-on: ubuntu-latest
    #container: ${{ secrets.DOCKER_REPO }}/actbuildx:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Set RELEASE_DATE
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.buildx-cache.bookworm
            /tmp/.buildx-cache.latest
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx- 

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker AMD64/ARM64 image for latest
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: false
          tags: |
            ${{ secrets.DOCKER_REPO }}/vbox:latest
            ${{ secrets.DOCKER_REPO }}/vbox:${{ env.RELEASE_DATE }}
          cache-from: type=local,src=/tmp/.buildx-cache.latest
          cache-to: type=local,dest=/tmp/.buildx-cache-new.latest

      - name: Rotate the cache for latest
        run: |
          rm -rf /tmp/.buildx-cache.latest
          mv /tmp/.buildx-cache-new.latest /tmp/.buildx-cache.latest

      - name: Build and push Docker AMD64/ARM64 image for bookworm
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.bookworm
          platforms: linux/amd64, linux/arm64
          push: false
          tags: |
            ${{ secrets.DOCKER_REPO }}/vbox:bookworm
            ${{ secrets.DOCKER_REPO }}/vbox:bookworm-${{ env.RELEASE_DATE }}
          cache-from: type=local,src=/tmp/.buildx-cache.bookworm
          cache-to: type=local,dest=/tmp/.buildx-cache-new.bookworm

      - name: Rotate the cache for bookworm
        run: |
          rm -rf /tmp/.buildx-cache.bookworm
          mv /tmp/.buildx-cache-new.bookworm /tmp/.buildx-cache.bookworm
